### PR TITLE
update regional data

### PR DESCRIPTION
**Pull request by TKDMaster12**
@Mandalorian007 

add new regional data
small clean up for dark theme
fixed speed filter

### CODE REVIEW

**Comment by TKDMaster12** [comment]
@Mandalorian007 
cant get type filter to work. 
The problem is in the backend, when building the search query, you call it in your inBuilder function you make all chars capital but in the json database types are lowercase. 
Do you want to make duplicate function that doesnt contain the one line or add that part of the query to the if statement

**Comment by Mandalorian007** [comment]
@TKDMaster12 Which search filters are broken?  I use that function multiple times so I want to see if it's everything using that function or just one of them.  Ideally I would just swap the function to lowercase

**Comment by TKDMaster12** [comment]
@Mandalorian007 
Only the type filter is broken (humanoid, dragon, beast, etc). The size and alignment filter work fine. 
If I remember correctly those are the only three that use it.

**Comment by TKDMaster12** [comment]
@Mandalorian007 
its probably easiest to remove the case sensitive line and on the frontend change the size values to all caps

**Comment by Mandalorian007** [comment]
hmm maybe I should make all the database compares case sensitive.  The other option which might be best long term is to make the Types all enums.  That way it would behave exactly like the others.  What do you think?

**Comment by TKDMaster12** [comment]
I would make the Types enums so they are the same as the others.
How would making the Types enums, fix the case sensitive problem?

**Comment by TKDMaster12** [comment]
@Mandalorian007 
Any ideas on which way you want to go about doing this?

**Pull request closed without merging**
