### PR TITLE
Add Validation to combatantForm

### PR DESCRIPTION
**Pull request by TKDMaster12**
@Mandalorian007 
Add Validation to combatantForm

### CODE REVIEW

**Comment by TKDMaster12** [comment]
@Mandalorian007 
Do you think we should add a field for the currentInitiative? or just wait to type it in new round

**Comment by Mandalorian007** [comment]
@TKDMaster12 I think waiting for the new round is perfectly fine since we just have it default to 0 when adding a new combatant

**Comment by Mandalorian007** [comment]
Awesome!  Can't wait :)

**Comment by Mandalorian007** [comment]
Hopefully, I will have some significant work done with the monsters soon.  it's taking much longer than I was expecting

**Comment by TKDMaster12** [comment]
@Mandalorian007 
Validation Complete 
Got to check later to make sure no new bugs.

**Comment by Mandalorian007** [comment]
@TKDMaster12 Awesome whenever your testing is good, merge away!

**Pull request merged**
