### PR TITLE
Customization options

### PR DESCRIPTION
**Pull request by TKDMaster12**
@Mandalorian007 
Started the dark theme
Added ability to change primary and secondary colors
Got to work out a few more kinks

### CODE REVIEW

**Comment by Mandalorian007** [comment]
This is awesome!

**Comment by TKDMaster12** [comment]
@Mandalorian007 
got most of the problems fixed.
new combatant page  -   good
encounter page  --  how do you feel about the colors of the table in dark mode?
npc page -- if you click on a monster for details, i feel like the red and blue dont look good in dark mode?any thaughts?

**Comment by Mandalorian007** [comment]
@TKDMaster12 I just tried to run it locally after your updates, but I am getting an error:
```
[INFO] ./src/main/js/encounterDrawer.tsx
[INFO] [tsl] ERROR in /Users/mcf/projects/dnd-encounter-helper/src/main/js/encounterDrawer.tsx(257,17)
[INFO]       TS2345: Argument of type '{ palette: { type: any; primary: { main: any; }; secondary: { main: any; }; }; typography: { useNextVariants: boolean; }; }' is not assignable to parameter of type 'ThemeOptions'.
[INFO]   Types of property 'typography' are incompatible.
[INFO]     Type '{ useNextVariants: boolean; }' is not assignable to type 'TypographyOptions | ((palette: Palette) => TypographyOptions)'.
[INFO]       Object literal may only specify known properties, and 'useNextVariants' does not exist in type 'TypographyOptions | ((palette: Palette) => TypographyOptions)'.

```

**Comment by Mandalorian007** [comment]
removed a few lines to get it to build.

In Darkmode I see 2 problems with the table.  The textboxes didn't change themes so it's too aggressive.  The green highlight is also too strong in my opinion.

I also agree that the red and blue doesn't look great in Dark Mode on the details page.  Maybe a Green instead of the red in dark mode?  Not sure what to think about the blue

**Comment by TKDMaster12** [comment]
@Mandalorian007 
I fixed the textboxes in the table

I am not getting your error when compiling all the code. Did you merge that change already?

**Comment by Mandalorian007** [comment]
I didn't make any changes after trying the new build I am seeing new errors:
```
[INFO] ./src/main/js/encounterDrawer.tsx
[INFO] [tsl] ERROR in /Users/mcf/projects/dnd-encounter-helper/src/main/js/encounterDrawer.tsx(257,17)
[INFO]       TS2345: Argument of type '{ palette: { type: any; primary: { main: any; }; secondary: { main: any; }; }; typography: { useNextVariants: boolean; }; }' is not assignable to parameter of type 'ThemeOptions'.
[INFO]   Types of property 'typography' are incompatible.
[INFO]     Type '{ useNextVariants: boolean; }' is not assignable to type 'TypographyOptions | ((palette: Palette) => TypographyOptions)'.
[INFO]       Object literal may only specify known properties, and 'useNextVariants' does not exist in type 'TypographyOptions | ((palette: Palette) => TypographyOptions)'.
[INFO] 
[INFO] ERROR in /Users/mcf/projects/dnd-encounter-helper/src/main/js/encounterDrawer.tsx
[INFO] ./src/main/js/encounterDrawer.tsx
[INFO] [tsl] ERROR in /Users/mcf/projects/dnd-encounter-helper/src/main/js/encounterDrawer.tsx(267,37)
[INFO]       TS2322: Type '"h6"' is not assignable to type 'Style'.
[INFO] 
[INFO] ERROR in /Users/mcf/projects/dnd-encounter-helper/src/main/js/newNpcsFromTemplateForm.tsx
[INFO] ./src/main/js/newNpcsFromTemplateForm.tsx
[INFO] [tsl] ERROR in /Users/mcf/projects/dnd-encounter-helper/src/main/js/newNpcsFromTemplateForm.tsx(77,20)
[INFO]       TS2304: Cannot find name 'theme'.
```

**Pull request merged**
