### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by TKDMaster12**

### CODE REVIEW

**Comment by TKDMaster12** [comment]
@Mandalorian007 
moved the css to separate function
add comments

**Comment by Mandalorian007** [comment]
@TKDMaster12 huge improvement!

I also thought of another way we can handle the state!

We could copy the props.combatants into the internal state of the CombatantList component.  Then you can just update the local state when the field is "NaN", but when it is a number again you can call updateCombatant which will force a refresh on the ComponentList as well!

**Comment by TKDMaster12** [comment]
@Mandalorian007 
I copied the props.combatants to the internal state of CombatantList

**Comment by Mandalorian007** [comment]
@TKDMaster12 This is awesome!!!!  I am merging this :)

**Pull request merged**
