### PR TITLE
Monsterdetails

### PR DESCRIPTION
**Pull request by TKDMaster12**

### CODE REVIEW

**Comment by TKDMaster12** [comment]
need to add

damage vulnerabilities
damage resistance
damage immunities
condition immunities
senses

**Comment by Mandalorian007** [comment]
@TKDMaster12 Just fixed speed: https://github.com/Mandalorian007/dnd-encounter-helper/pull/40

**Comment by TKDMaster12** [comment]
@Mandalorian007 
when you get a chance can you add damage vulnerabilities to monsterConverter.
Is there any reason you split languages into an array?

**Comment by Mandalorian007** [comment]
@TKDMaster12 

Good catch on forgetting damage vulnerabilities I will try and get that added today

Languages got moved into an array since that is how they came this time. (no real reason in particular)

I took a really quick look at the search bug.  The API seems to be returning the correct data under the hood, so it must be some sort of refresh issue on our UI.

For now just leave the @ Strings.  I am trying to think of a way to manage them on the backend so it's easy to adjust CR

**Comment by Mandalorian007** [comment]
@TKDMaster12 Vulnerability conversion added: https://github.com/Mandalorian007/dnd-encounter-helper/pull/41

**Comment by Mandalorian007** [comment]
@TKDMaster12 Just finished the initial work for parsing Spellcasting: https://github.com/Mandalorian007/dnd-encounter-helper/pull/42

Only remaining things needing conversion logic should be Spellcasting and Variant info.  Variant info I may need to re-do the parsing logic for a better model.

**Comment by TKDMaster12** [comment]
@Mandalorian007 
okay i am going to merge. If we decide to "search by language we can add it back later

**Pull request merged**
